In [64]:
import numpy as np
import pandas as pd


# 1. Basic Data Structure

### create data set:

In [65]:
vector_array = np.arange(5, 17)
vector_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [66]:
np.random.seed(42)
feature_matrix = np.random.randint(9, size=(3, 4))
print("feature_matrix:\n", feature_matrix)
print("size:", feature_matrix.size)
print("ndim:", feature_matrix.ndim)
print("shape:", feature_matrix.shape)
print("dtype:", feature_matrix.dtype)

print("\nvector_array:\n", vector_array)
print("size:", vector_array.size)
print("ndim:", vector_array.ndim)
print("shape:", vector_array.shape)
print("dtype:", vector_array.dtype)

feature_matrix:
 [[6 3 7 4]
 [6 2 6 7]
 [4 3 7 7]]
size: 12
ndim: 2
shape: (3, 4)
dtype: int64

vector_array:
 [ 5  6  7  8  9 10 11 12 13 14 15 16]
size: 12
ndim: 1
shape: (12,)
dtype: int64

### indexing, slicing, subsetting:

In [67]:
#indexing
feature_matrix[1, 2]

np.int64(6)

In [68]:
#slicing
feature_matrix[0]

array([6, 3, 7, 4])

In [69]:
feature_matrix[:,-1]

array([4, 7, 7])

In [70]:
feature_matrix[:2, 2:]

array([[7, 4],
       [6, 7]])

### Array Manipulation (change array shape)

In [71]:
feature_matrix.reshape(4, 3)

array([[6, 3, 7],
       [4, 6, 2],
       [6, 7, 4],
       [3, 7, 7]])

In [72]:
# flatten:
feature_matrix.ravel()

array([6, 3, 7, 4, 6, 2, 6, 7, 4, 3, 7, 7])

### DataSet combination:

In [73]:
identity_matrix = np.ones((3, 4))

In [74]:
np.vstack((feature_matrix, identity_matrix))

array([[6., 3., 7., 4.],
       [6., 2., 6., 7.],
       [4., 3., 7., 7.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
vector = np.array([[10], [20], [30]])
vector

array([[10],
       [20],
       [30]])

In [76]:
np.hstack((feature_matrix, vector))

array([[ 6,  3,  7,  4, 10],
       [ 6,  2,  6,  7, 20],
       [ 4,  3,  7,  7, 30]])

# 2. Data Preprocessing and Numerical Operation

### Create Dataset

In [77]:
np.random.seed(101)
scores = np.random.randint(50, 100, size=(15, 3))
scores

array([[81, 61, 67],
       [56, 73, 61],
       [97, 59, 63],
       [90, 54, 90],
       [78, 50, 96],
       [55, 62, 79],
       [90, 99, 69],
       [97, 58, 79],
       [84, 94, 58],
       [69, 60, 62],
       [81, 93, 73],
       [50, 91, 59],
       [97, 58, 86],
       [69, 85, 78],
       [57, 60, 89]])

In [78]:
scores[1][0]

np.int64(56)

### Data Analize

In [79]:
col_mean = np.mean(scores, axis=0)
col_mean

array([76.73333333, 70.46666667, 73.93333333])

In [80]:
std_scores = np.std(scores, axis=0)
std_scores

array([15.91840305, 16.38644426, 12.01369589])

In [81]:
max_score = np.max(scores, axis=0)[2]
max_score

np.int64(96)

In [82]:
row_mean = np.mean(scores, axis=1)
row_mean

array([69.66666667, 63.33333333, 73.        , 78.        , 74.66666667,
       65.33333333, 86.        , 78.        , 78.66666667, 63.66666667,
       82.33333333, 66.66666667, 80.33333333, 77.33333333, 68.66666667])

### Broadcasting

In [83]:
curved_scores = np.array(5)
print(curved_scores + scores[:, 5])
scores

IndexError: index 5 is out of bounds for axis 1 with size 3

### Normalization

In [ ]:
normalized_scores = (scores - col_mean) / std_scores
normalized_scores

array([[ 0.26803359, -0.57771329, -0.5771191 ],
       [-1.30247571,  0.15459933, -1.07654909],
       [ 1.27315954, -0.6997654 , -0.91007242],
       [ 0.83341693, -1.00489566,  1.33736252],
       [ 0.07957247, -1.24899986,  1.83679251],
       [-1.36529608, -0.51668724,  0.42174088],
       [ 0.83341693,  1.74127668, -0.41064244],
       [ 1.27315954, -0.76079145,  0.42174088],
       [ 0.4564947 ,  1.43614642, -1.32626408],
       [-0.48581088, -0.63873934, -0.99331076],
       [ 0.26803359,  1.37512037, -0.07768911],
       [-1.67939794,  1.25306827, -1.24302575],
       [ 1.27315954, -0.76079145,  1.0044092 ],
       [-0.48581088,  0.88691196,  0.33850255],
       [-1.23965534, -0.63873934,  1.25412419]])

In [ ]:
min_normalized_scores = np.mean(normalized_scores, axis=0)
print(min_normalized_scores)
std_normalized_scores = np.std(normalized_scores, axis=0)
print(std_normalized_scores)

[-7.40148683e-17 -9.62193288e-17 -2.66453526e-16]
[1. 1. 1.]

# 3. Data Filtering & Feature Engineering

### Boolean Mask

In [ ]:
high_scores = scores > 95
high_scores

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
high_scores_quantity = np.sum(scores > 95)
high_scores_quantity

np.int64(5)

In [ ]:
high_performance_score = scores[scores>95]
high_performance_score

array([97, 96, 99, 97, 97])

In [ ]:
low_scores = scores[scores[:, 0] <= 70]
mean_low = np.mean(low_scores[:, 1])
print("students who get score equal or under 70 at exam 1:\n", low_scores)
print("avarage scores of these students:\n", mean_low)

students who get score equal or under 70 at exam 1:
 [[56 73 61]
 [55 62 79]
 [69 60 62]
 [50 91 59]
 [69 85 78]
 [57 60 89]]
avarage scores of these students:
 71.83333333333333

### Feature Engineering

In [ ]:
ave_scores = np.mean(scores, axis=1)
print(ave_scores)
pass_fail = np.bool(np.where(ave_scores<65, False, ave_scores))
pass_fail

[69.66666667 63.33333333 73.         78.         74.66666667 65.33333333
 86.         78.         78.66666667 63.66666667 82.33333333 66.66666667
 80.33333333 77.33333333 68.66666667]

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True])

### Complicated Filtering

In [ ]:
top_students = np.all(scores>=60, axis=1)
if not np.any(top_students):
    print("No top student!")
else:
    print(np.where(top_students))
    print(scores[top_students])

(array([ 0,  6,  9, 10, 13]),)
[[81 61 67]
 [90 99 69]
 [69 60 62]
 [81 93 73]
 [69 85 78]]

# 4. ML

### read data

In [ ]:
df = pd.read_csv("titanic.csv")

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Initial Analize

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Data Selection

In [ ]:
df['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
df['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
df['Survived'].dtype

dtype('int64')

In [ ]:
df[["Age","Pclass",'Sex']]

      Age  Pclass     Sex
0    22.0       3    male
1    38.0       1  female
2    26.0       3  female
3    35.0       1  female
4    35.0       3    male
..    ...     ...     ...
886  27.0       2    male
887  19.0       1  female
888   NaN       3  female
889  26.0       1    male
890  32.0       3    male

[891 rows x 3 columns]

In [ ]:
df.loc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [ ]:
df.iloc[:5,:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

### Data Filtering

In [ ]:
np.sum(df['Survived'])

np.int64(342)

In [ ]:
survivors = pd.DataFrame(df[df["Survived"] == 1])
survivors

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
np.sum(survivors['Sex']=='male')

np.int64(109)

In [ ]:
first_class = pd.DataFrame(df[df['Pclass']==1])
first_class

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

# 5. Cleaning and PreProcessing

### Identifing Missing Values

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df_cleaned = df.drop('Cabin', axis='columns')
df_cleaned

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

### Handling Missing Values

In [ ]:
median = df['Age'].median()
median

np.float64(28.0)

In [ ]:
df_cleaned['Age'] = df_cleaned['Age'].fillna(median)
df_cleaned

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
mode = df['Embarked'].mode()
mode

0    S
Name: Embarked, dtype: str

In [ ]:
df_cleaned['Embarked'] = df_cleaned['Embarked'].fillna(mode[0])
df_cleaned

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df_cleaned.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Process Finalization

In [ ]:
df_cleaned['Pclass'] = df_cleaned['Pclass'].astype({'Pclass':str})
df_cleaned['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: str

# 6. Feature Engineering and Group Analysis

### Creating New Features from Existing Ones

In [ ]:
df_cleaned['FamilySize'] = df_cleaned['SibSp'] + df_cleaned['Parch']
df_cleaned

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,S,0
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0

### Extracting Information to Build Features

In [84]:
df_cleaned['Title'] = df_cleaned['Name'].str.extract(pat=r",\s*(Mr|Mrs|Miss)\b")
df_cleaned['Title'].unique()

<StringArray>
['Mr', 'Mrs', 'Miss', nan]
Length: 4, dtype: str

### Group Analysis for Gaining Insights

In [ ]:
survived_rate = df_cleaned.groupby('Sex')['Survived'].mean()
print(survived_rate)

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [ ]:
class_group = df_cleaned.groupby('Pclass')['Survived'].mean()
print(class_group)

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [90]:
rate = df_cleaned.groupby(['Sex', 'Pclass'])['Survived'].mean()
rate

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

### Binning Numerical Data

In [ ]:
def age_groups(age):
    if age < 18:
        return 'Child'
    elif 18 < age < 65:
        return 'Adult'
    else:
        return 'Senior'
    
df_cleaned['AgeGroup'] = df_cleaned['Age'].apply(age_groups)
df_cleaned

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Title,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,Mr,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Mrs,Adult
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Miss,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Mrs,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,Mr,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,NaN,Adult
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,S,Miss,Adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,Miss,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,Mr,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,Mr,Adult